export const ASSIGNEES: string[] = [
  'Maya Ellison',
  'Darius Okonkwo',
  'Priya Raman',
  'Callum Fitzgerald',
  'Sofia Marchetti',
  'Jamal Whitfield',
  'Elena Vasquez',
  'Theo Lindqvist',
  'Amara Diallo',
  'Nathan Brooks',
  'Yuki Tanaka',
  'Isabella Romano',
  'Marcus Delgado',
  'Freya Andersen',
  'Omar Haddad',
  'Grace Chukwu',
  "Liam O'Sullivan",
  'Nadia Petrova',
  'Ravi Kapoor',
  'Chloe Beaumont',
];
